spring.application.name=OS2indberetning
server.port=9090
#server.port=9091

spring.main.allow-circular-references=true
spring.jpa.open-in-view=true
spring.thymeleaf.cache=true

server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

management.endpoints.web.base-path=/manage

### persistent cookie, 4 hours expiry ###
server.servlet.session.persistent=true
server.servlet.session.cookie.max-age=14400
server.servlet.session.timeout=4h

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=SPRING_SESSION

# max file size
spring.servlet.multipart.max-file-size=200MB
# max request size
spring.servlet.multipart.max-request-size=200MB


## Saml module config ##
di.saml.pages.nonsecured=/,/error,/webjars/**,/css/**,/js/**,/img/**,/api/**,/internal/api/**,/appapi/**,/manage/**,/favicon.ico
di.saml.pages.csrfBypass=/api/**,/manage/**,/appapi/**,/internal/api/**

# No Swagger for you
springdoc.api-docs.enabled=false

### Spring Session config ###
spring.session.jdbc.cleanup-cron=${random.int(60)} ${random.int(5)}/5 * * * *

