//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ApplicationServices.SdKoersel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.sd.dk/sdws/AnsaettelseKoerselOpret20170501", ConfigurationName="SdKoersel.AnsaettelseKoerselOpret20170501PortType")]
    public interface AnsaettelseKoerselOpret20170501PortType {
        
        // CODEGEN: Generating message contract since the operation AnsaettelseKoerselOpret20170501Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws-indberetning/services/AnsaettelseKoerselOpret20170501", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse AnsaettelseKoerselOpret20170501Operation(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.sd.dk/sdws-indberetning/services/AnsaettelseKoerselOpret20170501", ReplyAction="*")]
        System.Threading.Tasks.Task<Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse> AnsaettelseKoerselOpret20170501OperationAsync(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01")]
    public partial class AnsaettelseKoerselOpretInputType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string brugerIdentifikatorField;
        
        private string item1Field;
        
        private Item1ChoiceType item1ElementNameField;
        
        private string registreringTypeIdentifikatorField;
        
        private System.DateTime koerselDatoField;
        
        private decimal kilometerMaalField;
        
        private string kontoNummerIdentifikatorField;
        
        private bool godkendtIndikatorField;
        
        private bool kontrolleretIndikatorField;
        
        private bool dokumentationEksternIndikatorField;
        
        private bool regel60DageIndikatorField;
        
        private string registreringNummerIdentifikatorField;
        
        private string aarsagTekstField;
        
        private string koertFraTekstField;
        
        private string koertTilTekstField;
        
        private string[] koertViaTekstField;
        
        private string item2Field;
        
        private Item2ChoiceType item2ElementNameField;
        
        private string konteringAfvigendeStillingIdentifikatorField;
        
        private string konteringAfvigendeTjenesteKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstitutionIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("InstitutionUUIDIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BrugerIdentifikator {
            get {
                return this.brugerIdentifikatorField;
            }
            set {
                this.brugerIdentifikatorField = value;
                this.RaisePropertyChanged("BrugerIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnsaettelseIdentifikator", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("AnsaettelseUUIDIdentifikator", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
        public string Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item1ChoiceType Item1ElementName {
            get {
                return this.item1ElementNameField;
            }
            set {
                this.item1ElementNameField = value;
                this.RaisePropertyChanged("Item1ElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=5)]
        public string RegistreringTypeIdentifikator {
            get {
                return this.registreringTypeIdentifikatorField;
            }
            set {
                this.registreringTypeIdentifikatorField = value;
                this.RaisePropertyChanged("RegistreringTypeIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", DataType="date", Order=6)]
        public System.DateTime KoerselDato {
            get {
                return this.koerselDatoField;
            }
            set {
                this.koerselDatoField = value;
                this.RaisePropertyChanged("KoerselDato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=7)]
        public decimal KilometerMaal {
            get {
                return this.kilometerMaalField;
            }
            set {
                this.kilometerMaalField = value;
                this.RaisePropertyChanged("KilometerMaal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string KontoNummerIdentifikator {
            get {
                return this.kontoNummerIdentifikatorField;
            }
            set {
                this.kontoNummerIdentifikatorField = value;
                this.RaisePropertyChanged("KontoNummerIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool GodkendtIndikator {
            get {
                return this.godkendtIndikatorField;
            }
            set {
                this.godkendtIndikatorField = value;
                this.RaisePropertyChanged("GodkendtIndikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool KontrolleretIndikator {
            get {
                return this.kontrolleretIndikatorField;
            }
            set {
                this.kontrolleretIndikatorField = value;
                this.RaisePropertyChanged("KontrolleretIndikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool DokumentationEksternIndikator {
            get {
                return this.dokumentationEksternIndikatorField;
            }
            set {
                this.dokumentationEksternIndikatorField = value;
                this.RaisePropertyChanged("DokumentationEksternIndikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=12)]
        public bool Regel60DageIndikator {
            get {
                return this.regel60DageIndikatorField;
            }
            set {
                this.regel60DageIndikatorField = value;
                this.RaisePropertyChanged("Regel60DageIndikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/registreringnummer/xml/schemas/20080401/", Order=13)]
        public string RegistreringNummerIdentifikator {
            get {
                return this.registreringNummerIdentifikatorField;
            }
            set {
                this.registreringNummerIdentifikatorField = value;
                this.RaisePropertyChanged("RegistreringNummerIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=14)]
        public string AarsagTekst {
            get {
                return this.aarsagTekstField;
            }
            set {
                this.aarsagTekstField = value;
                this.RaisePropertyChanged("AarsagTekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=15)]
        public string KoertFraTekst {
            get {
                return this.koertFraTekstField;
            }
            set {
                this.koertFraTekstField = value;
                this.RaisePropertyChanged("KoertFraTekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sd:snitflader:2012.02.01", Order=16)]
        public string KoertTilTekst {
            get {
                return this.koertTilTekstField;
            }
            set {
                this.koertTilTekstField = value;
                this.RaisePropertyChanged("KoertTilTekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KoertViaTekst", Order=17)]
        public string[] KoertViaTekst {
            get {
                return this.koertViaTekstField;
            }
            set {
                this.koertViaTekstField = value;
                this.RaisePropertyChanged("KoertViaTekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KonteringAfvigendeEnhedIdentifikator", typeof(string), Order=18)]
        [System.Xml.Serialization.XmlElementAttribute("KonteringAfvigendeEnhedUUIDIdentifikator", typeof(string), Order=18)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item2ElementName")]
        public string Item2 {
            get {
                return this.item2Field;
            }
            set {
                this.item2Field = value;
                this.RaisePropertyChanged("Item2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item2ChoiceType Item2ElementName {
            get {
                return this.item2ElementNameField;
            }
            set {
                this.item2ElementNameField = value;
                this.RaisePropertyChanged("Item2ElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string KonteringAfvigendeStillingIdentifikator {
            get {
                return this.konteringAfvigendeStillingIdentifikatorField;
            }
            set {
                this.konteringAfvigendeStillingIdentifikatorField = value;
                this.RaisePropertyChanged("KonteringAfvigendeStillingIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string KonteringAfvigendeTjenesteKode {
            get {
                return this.konteringAfvigendeTjenesteKodeField;
            }
            set {
                this.konteringAfvigendeTjenesteKodeField = value;
                this.RaisePropertyChanged("KonteringAfvigendeTjenesteKode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        InstitutionIdentifikator,
        
        /// <remarks/>
        InstitutionUUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", IncludeInSchema=false)]
    public enum Item1ChoiceType {
        
        /// <remarks/>
        AnsaettelseIdentifikator,
        
        /// <remarks/>
        AnsaettelseUUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", IncludeInSchema=false)]
    public enum Item2ChoiceType {
        
        /// <remarks/>
        KonteringAfvigendeEnhedIdentifikator,
        
        /// <remarks/>
        KonteringAfvigendeEnhedUUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01")]
    public partial class AnsaettelseKoerselOpret20170501Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AnsaettelseKoerselOpretInputType inddataStrukturField;
        
        private string registreringIdentifikatorField;
        
        private System.DateTime dannetDatoTidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AnsaettelseKoerselOpretInputType InddataStruktur {
            get {
                return this.inddataStrukturField;
            }
            set {
                this.inddataStrukturField = value;
                this.RaisePropertyChanged("InddataStruktur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegistreringIdentifikator {
            get {
                return this.registreringIdentifikatorField;
            }
            set {
                this.registreringIdentifikatorField = value;
                this.RaisePropertyChanged("RegistreringIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dannetDatoTid {
            get {
                return this.dannetDatoTidField;
            }
            set {
                this.dannetDatoTidField = value;
                this.RaisePropertyChanged("dannetDatoTid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsaettelseKoerselOpret20170501OperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", Order=0)]
        public Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpretInputType AnsaettelseKoerselOpret;
        
        public AnsaettelseKoerselOpret20170501OperationRequest() {
        }
        
        public AnsaettelseKoerselOpret20170501OperationRequest(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpretInputType AnsaettelseKoerselOpret) {
            this.AnsaettelseKoerselOpret = AnsaettelseKoerselOpret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsaettelseKoerselOpret20170501OperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:sd:snitflader:2017.05.01", Order=0)]
        public Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501Type AnsaettelseKoerselOpret20170501;
        
        public AnsaettelseKoerselOpret20170501OperationResponse() {
        }
        
        public AnsaettelseKoerselOpret20170501OperationResponse(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501Type AnsaettelseKoerselOpret20170501) {
            this.AnsaettelseKoerselOpret20170501 = AnsaettelseKoerselOpret20170501;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnsaettelseKoerselOpret20170501PortTypeChannel : Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnsaettelseKoerselOpret20170501PortTypeClient : System.ServiceModel.ClientBase<Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType>, Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType {
        
        public AnsaettelseKoerselOpret20170501PortTypeClient() {
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnsaettelseKoerselOpret20170501PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType.AnsaettelseKoerselOpret20170501Operation(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request) {
            return base.Channel.AnsaettelseKoerselOpret20170501Operation(request);
        }
        
        public Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501Type AnsaettelseKoerselOpret20170501Operation(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpretInputType AnsaettelseKoerselOpret) {
            Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest inValue = new Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest();
            inValue.AnsaettelseKoerselOpret = AnsaettelseKoerselOpret;
            Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse retVal = ((Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType)(this)).AnsaettelseKoerselOpret20170501Operation(inValue);
            return retVal.AnsaettelseKoerselOpret20170501;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse> Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType.AnsaettelseKoerselOpret20170501OperationAsync(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest request) {
            return base.Channel.AnsaettelseKoerselOpret20170501OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationResponse> AnsaettelseKoerselOpret20170501OperationAsync(Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpretInputType AnsaettelseKoerselOpret) {
            Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest inValue = new Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501OperationRequest();
            inValue.AnsaettelseKoerselOpret = AnsaettelseKoerselOpret;
            return ((Core.ApplicationServices.SdKoersel.AnsaettelseKoerselOpret20170501PortType)(this)).AnsaettelseKoerselOpret20170501OperationAsync(inValue);
        }
    }
}
