version: "3"

services:
  os2db:
    image: mysql:5.7.24
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./os2db/dump:/os2dbdump/
      - ./os2db/lowercase.cnf:/etc/mysql/mysql.conf.d/lowercase.cnf

