### IDP DISCOVERY - At least one IDP must be configured ###
indberet.idps.NORMAL.entityId=https://login-idp.digital-identity.dk/
indberet.idps.NORMAL.metadataUrl=https://login-idp.digital-identity.dk/sso/saml/metadata

indberet.idps.MITID.entityId=https://mitid-emulator.test:8080/
indberet.idps.MITID.metadataUrl=https://mitid-emulator.test:8080/sso/saml/metadata

### Dev Mode ###
indberet.developmentMode=true
#logging.level.org.springframework.security=DEBUG
#logging.level.dk.digitalidentity.emailService=DEBUG
#logging.level.dk.digitalidentity.samlmodule=DEBUG
springdoc.api-docs.enabled=true

report.service.enabled=false

spring.thymeleaf.prefix=file:src/main/resources/templates/
resources.static-locations=file:src/main/resources/static/
resources.cache.period=0

#indberet.calculationPreference=shortest
#indberet.hideDropDown=true
#indberet.logAllAppReports=true

### Task management - Copy to application.development.properties to change task runtimes without modifying code ###
indberet.scheduled.enabled=true
#indberet.scheduled.deadlineEmailsEnabled=true
#indberet.scheduled.processEmailsForAddressWash=true
#indberet.scheduled.deadlineEmailsCron=0 #{new java.util.Random().nextInt(55)} 0/4 * * ?
#indberet.scheduled.exportOnetimePaymentsEnabled=true
#indberet.scheduled.exportOnetimePaymentsCron=0 #{new java.util.Random().nextInt(55)} 4 * * ?
#indberet.scheduled.processAddressesEnabled=true
#indberet.scheduled.processAddressesCron=0 */10 * ? * *
#indberet.scheduled.sixtyDayRuleEnabled=true
#indberet.scheduled.sixtyDayRuleCron=0 #{new java.util.Random().nextInt(55)} 18 * * THU
#indberet.scheduled.sendRejectedEmailsEnabled=true
#indberet.scheduled.sendRejectedEmailsCron=0 0 8 * * *
#indberet.scheduled.sixtyDayRuleResetCron=0 #{new java.util.Random().nextInt(55)} 17 * * THU
#indberet.scheduled.updateApproversForPendingReportsEnabled=true
#indberet.scheduled.updateApproversForPendingReportsCron=0 #{new java.util.Random().nextInt(55)} #{new java.util.Random().nextInt(5)} 1/3 * ?
#indberet.scheduled.addressWashEmailsEnabled=true
#indberet.scheduled.addressWashEmailsCron=0/20 * * ? * *
#indberet.scheduled.updateStatisticsEnabled=true
#indberet.scheduled.updateStatisticsCron=* * * ? * *
#indberet.scheduled.cleanupOldAuditlogEnabled=true
#indberet.scheduled.cleanupOldAuditlogCron=0 #{new java.util.Random().nextInt(55)} 14 ? * WED
#indberet.scheduled.checkForTerminationsTaskEnabled=true
#indberet.scheduled.checkForTerminationsTaskCron=0 0 6 * * ?
#indberet.scheduled.cleanUpOldDataEnabled=true
#indberet.scheduled.cleanUpOldDataCron=* #{new java.util.Random().nextInt(55)} 5 * * ?
#indberet.scheduled.cleanUpTaskDryRun=true

### Email configuration - Copy to application.development.properties to change test email sending without exposing App-password ###
#email-service.enabled=true
#emailservice.send.cron=0/20 * * ? * *
#email-service.fromName=DI
#email-service.smtp.host=smtp.gmail.com
#email-service.smtp.email=mpo@digital-identity.dk
#email-service.smtp.username=mpo@digital-identity.dk
#email-service.smtp.password=REDACTED

### Toggle functionality ###
#indberet.allowNewReports=false

### Map and routing ###
indberet.map.mapServiceBaseUrl=https://api.dataforsyningen.dk/

#indberet.map.routeService=ORS
#indberet.map.openRouteServiceBaseUrl=http://route.digital-identity.dk/ors/
#indberet.map.openRouteServiceBaseUrl=https://api.openrouteservice.org/
#indberet.map.routeServiceApiKey= Put this setting in application.development.properties or .env

#indberet.map.routeService=SEPTIMA
#indberet.map.septimaBaseUrl= Put this setting in application.development.properties or .env
#indberet.map.septimaApikey= Put this setting in application.development.properties or .env

indberet.addressLookup.baseUrl=https://adressevaelger.dk
indberet.reverseGeoLookup.baseUrl=https://graphql.datafordeler.dk/DAR/v3

### Database ###
spring.datasource.url=jdbc:mysql://localhost:3306/indberetning?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=FILL_IN


### SSL ###
server.ssl.enabled=true
server.ssl.key-store=config/ssl-dev.pfx
server.ssl.key-store-password=Test1234
server.ssl.key-password=Test1234

## SAML-Module config ###
di.saml.idp.discovery=true
di.saml.sp.baseUrl=https://os2indberetning-dev:9090
di.saml.keystore.location=config/samlKeystore.pfx
di.saml.keystore.password=Test1234
di.saml.acceptSelfSigned=true


### Thymeleaf caching ###
spring.thymeleaf.cache=false


### KMD Opus Personale Engangsydelser API ###
indberet.scheduled.exportOnetimePaymentsEnabled=true
indberet.opus.municipalityCode=589
indberet.opus.apiBaseUrl=https://opus-api-test.test.apimanagement.eu10.hana.ondemand.com
#indberet.opus.onlyValidateUpdates=false
#indberet.opus.keystoreLocation=Put this setting in application.development.properties or .env
#indberet.opus.keystorePassword=Put this setting in application.development.properties or .env


### Import Api ###
indberet.api.apiKey=Test1234
indberet.api.maxUnknownOus=10


# import developer-specific file not included in git (use this file for username/password stuff etc. during development)
spring.config.import=optional:application.development.properties,optional:file:.env[.properties]
