CREATE TABLE reports (
    -- TODO: Their seems to many unnecessary fields. Can properly be optimized, but will get it working first
    id                      BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    status                  VARCHAR(255) NOT NULL,
    created_date            datetime NOT NULL,
    edited_date             datetime,
    closed_date             datetime,
    processed_date          datetime,
    drive_date              datetime NOT NULL,
    comment                 VARCHAR(255),
    person_id               BIGINT NOT NULL,
    approved_by_id          BIGINT,
    actual_leader_id        BIGINT,
    employment_id           BIGINT NOT NULL,
    distance                DOUBLE,
    raw_distance            DOUBLE,
    amount_to_reimburse     DOUBLE,
    purpose                 VARCHAR(255),
    km_rate                 DOUBLE,
    km_rate_type            VARCHAR(255),
    four_km_rule            BOOLEAN,
    home_to_border_distance DOUBLE,
    starts_at_home          BOOLEAN,
    ends_at_home            BOOLEAN,
    license_plate           VARCHAR(255),
    full_name               VARCHAR(255),
    override_cost_center    VARCHAR(255),
    override_psp_Element    VARCHAR(255),
    pay_type                INT,
    sequential_number       INT,
    calculation_type        VARCHAR(255),
    is_from_app             BOOLEAN,
    app_uuid                VARCHAR(255),
    user_comment            VARCHAR(255),
    route_id                BIGINT NOT NULL,
    is_extra_distance       BOOLEAN,
    is_round_trip           BOOLEAN,
    sixty_days_rule         BOOLEAN,
    is_divergent_address    BOOLEAN,

    FOREIGN KEY (person_id) REFERENCES persons(id),
    FOREIGN KEY (actual_leader_id) REFERENCES persons(id),
    FOREIGN KEY (approved_by_id) REFERENCES persons(id),
    FOREIGN KEY (employment_id) REFERENCES employments(id),
    FOREIGN KEY (route_id) REFERENCES routes(id)
);

ALTER TABLE gps_coordinates ADD FOREIGN KEY (report_id) REFERENCES reports(id);